name: house_worker
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+4

environment:
  sdk: 3.9.2

dependencies:
  # ライブラリが Flutter SDK によって固定されているため、バージョンを指定しない
  # https://github.com/dart-lang/sdk/blob/main/docs/Flutter-Pinned-Packages.md
  characters: any
  cloud_firestore: 6.1.0
  cloud_functions: 6.0.4
  cupertino_icons: ^1.0.8
  firebase_ai: 3.5.0
  firebase_analytics: 12.0.4
  firebase_auth: 6.1.2
  firebase_core: 4.2.1
  firebase_crashlytics: 5.0.4
  firebase_remote_config: 6.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 3.0.3
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  google_sign_in: ^7.0.0
  in_app_review: ^2.0.10
  logging: ^1.3.0
  package_info_plus: ^9.0.0
  riverpod: 3.0.3
  riverpod_annotation: 3.0.3
  share_plus: 12.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  cider: ^0.2.8
  custom_lint: 0.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  pedantic_mono: ^1.33.0
  riverpod_generator: 3.0.3
  riverpod_lint: 3.0.3
  shared_preferences_platform_interface: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
