name: house_worker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.7.2

dependencies:
  cloud_firestore:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_riverpod:
  flutter_slidable:
  freezed_annotation:
  google_fonts:
  intl:
  logging:
  package_info_plus:
  path_provider:
  riverpod:
  share_plus:
  url_launcher:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  mockito:
  pedantic_mono: ^1.30.0

flutter:
  uses-material-design: true
