name: CI / Client

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./client

jobs:
  check-code-spell:
    name: Check code spell
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1
        with:
          reviewdog_version: latest
      - name: Install Code Spell Checker
        run: npm install -g cspell
      - name: Check Code Spell
        run: cspell '**/*.{dart,swift,kt}' > cspell.log
      - name: Run reviewdog for Code Spell Checker
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat cspell.log | reviewdog -efm='%f:%l:%c - %m' -name='Code Spell Checker' -reporter='github-pr-review'

  lint-dart:
    name: Lint Dart
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1
        with:
          reviewdog_version: latest
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          working-directory: ./client
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: ./client/ios
      - name: Generate uncommitted Flutter files
        uses: ./.github/actions/generate-uncommitted-flutter-files
        with:
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
          firebase-options-dart-base64-prod: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_PROD }}
          working-parent-directory: ./client
          working-child-directory: ios
      - name: Generate automatic codes
        run: bundle exec fastlane generate
        working-directory: ./client/ios
      - name: Flutter analyze
        run: flutter analyze --fatal-infos > flutter-analyze.log
      - name: Display Flutter analyze log
        if: failure()
        run: cat flutter-analyze.log
      - name: Run reviewdog for Flutter Analyzer
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat flutter-analyze.log | reviewdog -efm='%#%t%.%# • %m • %f:%l:%c %r' -name='Flutter Analyzer' -reporter='github-pr-review'

  test-dart:
    name: Test Dart
    permissions:
      checks: write
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          working-directory: ./client
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: ./client/ios
      - name: Generate uncommitted Flutter files
        uses: ./.github/actions/generate-uncommitted-flutter-files
        with:
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
          firebase-options-dart-base64-prod: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_PROD }}
          working-parent-directory: ./client
          working-child-directory: ios
      - name: Run Flutter test
        run: flutter test --file-reporter json:flutter-test-results.log
        working-directory: ./client
      - uses: dorny/test-reporter@6e6a65b7a0bd2c9197df7d0ae36ac5cee784230c # v2
        if: success() || failure()
        with:
          name: "Test Flutter results"
          path: "flutter-test-results.log"
          reporter: "flutter-json"
          working-directory: ./client

  check-impact-ios:
    name: Check impact for building iOS
    runs-on: ubuntu-latest
    outputs:
      has-changed-related-files: ${{ steps.check-related-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Check related files
        id: check-related-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            client/ios/**
            client/.tool-versions
            client/pubspec.lock
  build-ios:
    name: Build iOS app
    needs: check-impact-ios
    if: needs.check-impact-ios.outputs.has-changed-related-files == 'true'
    runs-on: macos-15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          working-directory: ./client
      - name: Setup Xcode
        uses: ./.github/actions/setup-xcode
        with:
          working-directory: ./client
      - name: Setup Swift Package Manager
        uses: ./.github/actions/setup-spm
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: ./client/ios
      - name: Generate uncommitted Flutter files
        uses: ./.github/actions/generate-uncommitted-flutter-files
        with:
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
          firebase-options-dart-base64-prod: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_PROD }}
          working-parent-directory: ./client
          working-child-directory: ios
      - name: Generate uncommitted iOS files for dev
        uses: ./.github/actions/generate-uncommitted-ios-files-dev
        with:
          google-service-plist-base64-dev: ${{ secrets.GOOGLE_SERVICE_PLIST_BASE64_DEV }}
          working-directory: ./client
      - name: iOS build
        run: bundle exec fastlane ios build_dev_with_no_code_sign
        working-directory: ./client/ios

  check-impact-android:
    name: Check impact for building Android
    runs-on: ubuntu-latest
    outputs:
      has-changed-related-files: ${{ steps.check-related-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Check related files
        id: check-related-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            client/android/**
            client/.tool-versions
            client/pubspec.lock
  build-android:
    name: Build Android app
    needs: check-impact-android
    if: needs.check-impact-android.outputs.has-changed-related-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          working-directory: ./client
      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: ./client/android
      - name: Generate uncommitted Flutter files
        uses: ./.github/actions/generate-uncommitted-flutter-files
        with:
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
          firebase-options-dart-base64-prod: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_PROD }}
          working-parent-directory: ./client
          working-child-directory: android
      - name: Generate uncommitted Android files for dev
        uses: ./.github/actions/generate-uncommitted-android-files-dev
        with:
          google-service-json-base64-dev: ${{ secrets.GOOGLE_SERVICE_JSON_BASE64_DEV }}
          working-directory: ./client
      - name: Generate key store
        uses: ./.github/actions/generate-key-store
        with:
          keystore-jks-base64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          store-password: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          working-directory: ./client
      - name: Android build
        run: bundle exec fastlane android build_dev
        working-directory: ./client/android
